
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ths-gpu
  labels:
    app: ths-gpu
spec:
  selector:
    matchLabels:
      app: ths-gpu
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ths-gpu
    spec:
      containers:  
      - name: ths-gpu
        image: tharhtetsanucsm/gpu:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "2000m"
        env :
          - name : PORT
            value : '8080'
          - name : _SERVER
            value : 'stg'
