apiVersion: v1
kind: Service
metadata:
  name: rinna-generate-gpu-service
  namespace: default
  labels:
    app: rinna-generate-gpu

spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

  selector:
    app: rinna-generate-gpu